"""Test suite for python decompiler library."""

import datetime
import importlib
import os.path
import random
import tempfile
import unittest

import xdis.magics

from azul_plugin_python.decompiler.python_decompiler import (
    decompile,
    decompile_file,
    DecompileErrors,
)

from azul_bedrock.test_utils.file_manager import FileManager

test_script = b"print('Hello testing world!')"
test_script_name = "hello.py"
test_precompiled_name = os.path.join("bytecode", "hello.cpython-37.pyc")
test_precompiled_py314 = os.path.join("bytecode", "hello_world314.cpython-314.pyc")


class PyDecTest(unittest.TestCase):
    """Test class for python_decompiler."""

    @classmethod
    def setUpClass(cls):
        """Set up data required for testing."""
        cls.pyc_path_37 = os.path.join(os.path.dirname(__file__), test_precompiled_name)
        cls.pyc_path_314 = os.path.join(os.path.dirname(__file__), test_precompiled_py314)

        # read .pyc bytecode into memory
        with open(cls.pyc_path_37, "rb") as f:
            cls.hello_pyc = f.read()

        test_array = bytearray()
        random.seed()
        for _ in range(256):
            test_array.append(random.randint(0, 255))  # noqa: S311

        cls.random_bytes = bytes(test_array)

        cls.fake_pyc = bytes(importlib.util.MAGIC_NUMBER + cls.random_bytes)

        # replace bytecode header with one from different version and test
        # Put python 2.7 header onto 3.x code i.e. .pyc header is 16 bytes
        cls.misversioned = xdis.magics.int2magic(62211) + cls.hello_pyc[16:]

    def test_random_bytes(self):
        """Test with randomly generated bytes."""
        results = decompile(self.random_bytes)

        # Check the contents of the values
        self.assertEqual(results["error_type"], DecompileErrors.BadMagicNumber)
        self.assertEqual(results["error_msg"], DecompileErrors.BadMagicNumberMsg)

        # only error keys are not none
        num_results = 0
        for k in results.keys():
            if results[k] is not None:
                num_results += 1
        self.assertEqual(num_results, 2)

    def test_header_with_random_bytes(self):
        """Test with random bytes prepended with this Python version's magic number."""
        # this is handled by decompile checking output, not stdout anymore
        results = decompile(self.fake_pyc)

        self.assertIn("error_type", results)
        self.assertEqual(results["error_type"], DecompileErrors.PycdcLoading)

        self.assertIn("error_msg", results)
        self.assertEqual(results["error_msg"], DecompileErrors.PycdcLoadingMsg)

        self.assertEqual(len(results), 2)

    def test_hello_with_wrong_header(self):
        """Test compiled hello world with .pyc header replaced from that of Python 2.x."""

        # this is handled by decompile checking output, not stdout anymore
        results = decompile(self.fake_pyc)

        self.assertIn("error_type", results)
        self.assertEqual(results["error_type"], DecompileErrors.PycdcLoading)

        self.assertIn("error_msg", results)
        self.assertEqual(results["error_msg"], DecompileErrors.PycdcLoadingMsg)

        self.assertEqual(len(results), 2)

    def test_simple(self):
        """Test compiled hello world."""
        results = decompile(self.hello_pyc)

        # filename should match that of compiled file
        self.assertEqual(results["filename"], "hello.py")

        # version string
        self.assertEqual(results["version"], "3.7")

        # magic must match that of is this python version
        self.assertEqual(results["magic"], 3394)

        # test that source code matches
        # need to convert double quotes to single
        self.assertIn(test_script, results["source"])

        self.assertEqual(results["timestamp"], datetime.datetime(2021, 5, 7, 1, 54, 19))

    def test_simple_decompile_file(self):
        """Test compiled hello world."""
        results = decompile_file(self.pyc_path_37)

        # filename should match that of compiled file
        self.assertEqual(results["filename"], "hello.py")

        # version string
        self.assertEqual(results["version"], "3.7")

        # magic must match that of is this python version
        self.assertEqual(results["magic"], 3394)

        # test that source code matches
        # need to convert double quotes to single
        self.assertIn(test_script, results["source"])

        self.assertEqual(results["timestamp"], datetime.datetime(2021, 5, 7, 1, 54, 19))

    def test_simple_decompile_file_bad_extension(self):
        """Test compiled hello world."""
        with tempfile.NamedTemporaryFile() as pyc_no_ext_file:
            with open(self.pyc_path_37, "rb") as f:
                pyc_no_ext_file.write(f.read())
            pyc_no_ext_file.seek(0)

            results = decompile_file(pyc_no_ext_file.name)

            # verify symlink is removed.
            self.assertTrue(not os.path.exists(pyc_no_ext_file.name + ".pyc"))

            # filename should match that of compiled file
            self.assertEqual(results["filename"], "hello.py")

            # version string
            self.assertEqual(results["version"], "3.7")

            # magic must match that of is this python version
            self.assertEqual(results["magic"], 3394)

            # test that source code matches
            # need to convert double quotes to single
            self.assertIn(test_script, results["source"])

            self.assertEqual(results["timestamp"], datetime.datetime(2021, 5, 7, 1, 54, 19))

    def test_decompile_stdout_stderr_behaviour(self):
        """Test .pyc files are being pumped to stdout and stderr correctly."""
        # punycode.pyc, avaliable on VT
        data = FileManager().download_file_path("332ddaf2a9f501560f1f616c8b79ae169a765534820f3943e947616c8f22f57d")
        results = decompile_file(str(data))

        # It should have extracted the filename
        self.assertEqual(results["filename"], "punycode.py")

        # It should be a partial decompile
        self.assertTrue(results["partial_decompile"])

        # There should be content
        self.assertTrue(len(results["stdout_msg"]) > 0)

    def test_python314(self):
        """Test .pyc file of hello world compiled with Python 3.14"""
        results = decompile_file(self.pyc_path_314)

        # pycdc doesn't have the magic number for python3.14
        self.assertIn("error_type", results)
        self.assertEqual(results["error_type"], DecompileErrors.BadMagicNumber)

        self.assertIn("error_msg", results)
        self.assertEqual(results["error_msg"], DecompileErrors.BadMagicNumberMsg)

        self.assertEqual(len(results), 2)
